### ISSUE TITLE
Crash when streaming files in very large folders

### ISSUE THREAD

**Issue by sezuan** [kaczmarkiewiczp/rcloneExplorer#227]
Hi,

there's crash when I stream a video within a folder with about 900 videos:

```
12-23 14:44:23.818  3221  3221 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 587208)
12-23 14:44:23.819  3221  3221 D AndroidRuntime: Shutting down VM
12-23 14:44:23.819  3221  3221 E AndroidRuntime: FATAL EXCEPTION: main
12-23 14:44:23.819  3221  3221 E AndroidRuntime: Process: ca.pkay.rcloneexplorer, PID: 3221
12-23 14:44:23.819  3221  3221 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 587208 bytes
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3810)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-23 14:44:23.819  3221  3221 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 587208 bytes
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3802)
12-23 14:44:23.819  3221  3221 E AndroidRuntime:        ... 7 more
```

**Comment by x0b** [comment]
Can confirm - the error happens then Android tries to save the directory listing in https://github.com/kaczmarkiewiczp/rcloneExplorer/blob/cbeb04b1e3bb51c4129430c9bc6628c822aa72f8/app/src/main/java/ca/pkay/rcloneexplorer/Fragments/FileExplorerFragment.java#L340-L341 without checking whether it actually fits.
